const RESTAURANTS = [
  { name: "Amore Fantasia", address: "Norra Storgatan 1", area: "centrum" },
  { name: "Aroma Restaurang", address: "Norra Kyrkogatan 10", area: "centrum" },
  { name: "Backhaus Oceanhamnen", address: "Henckels Torg 4", area: "hamnen" },
  { name: "Badvakten", address: "Drottninggatan 95", area: "norr" },
  { name: "Banh Mi King", address: "Bruksgatan 34", area: "centrum" },
  { name: "Bar & Café Markelius", address: "Roskildegatan 1", area: "centrum" },
  { name: "Bara Vara", address: "Fågelsångsgatan 2", area: "centrum" },
  { name: "Barski", address: "Norra Storgatan 16", area: "centrum" },
  { name: "Bastard Burgers", address: "Södergatan 30", area: "söder" },
  { name: "Bastard Burgers City", address: "Norra Kyrkogatan 12", area: "centrum" },
  { name: "Batteritorget kök pub glass", address: "Batteritorget 1", area: "centrum" },
  { name: "Benchwarmers Brewing Co", address: "Industrigatan 121", area: "övrigt" },
  { name: "Benchwarmers Taproom", address: "Helsingörskajen 2", area: "hamnen" },
  { name: "Benchwarmers Taproom Oceanhamnen", address: "Vågbrytargränd 2", area: "hamnen" },
  { name: "Big Buddha", address: "Ålgränden 1", area: "centrum" },
  { name: "Bikten", address: "Mariagatan 10", area: "centrum" },
  { name: "Bistro 46", address: "Rååvägen 46", area: "söder" },
  { name: "Black Smith Burger", address: "Regementsvägen 4", area: "övrigt" },
  { name: "Blå Tuppen", address: "Väla Centrum", area: "övrigt" },
  { name: "Bollbrolyckan", address: "Bollbrogatan 4-6", area: "centrum" },
  { name: "Bosco", address: "Drottninggatan 15", area: "centrum" },
  { name: "Brasserie Le Coq Rouge", address: "Bruksgatan 19", area: "centrum" },
  { name: "Brasseriet", address: "Redaregatan 50", area: "hamnen" },
  { name: "Brewski Brew", address: "Cindersgatan 8", area: "hamnen" },
  { name: "Brunchoteket", address: "Drottninggatan 14", area: "centrum" },
  { name: "Brutale", address: "Drottninggatan 20-22", area: "centrum" },
  { name: "Brödernas", address: "Kungstorget 8", area: "centrum" },
  { name: "Bullangeriet Fikabar", address: "Kullagatan 8", area: "centrum" },
  { name: "Bulls Biljard", address: "Norra Strandgatan 32", area: "hamnen" },
  { name: "Bågen Mat & Bar", address: "Grepgatan 38", area: "övrigt" },
  { name: "Båten Restaurang & Bar", address: "Helsingörskajen 102", area: "hamnen" },
  { name: "Café & Restaurang Tegel", address: "Ytterövägen 167", area: "övrigt" },
  { name: "Café 1886", address: "Drottninggatan 30", area: "centrum" },
  { name: "Café Due", address: "Mariagatan 2", area: "centrum" },
  { name: "Cafe Etoile", address: "Drottninggatan 27", area: "centrum" },
  { name: "Café Mezo / Firavîn", address: "Södra Storgatan 3", area: "centrum" },
  { name: "Cafe Viva", address: "Södra Storgatan 6", area: "centrum" },
  { name: "Chateau Foret", address: "Södra Storgatan 19", area: "centrum" },
  { name: "Chattanoga", address: "Stattena Centrum", area: "övrigt" },
  { name: "Chiang Mai Thai Kitchen", address: "Bruksgatan 29", area: "centrum" },
  { name: "China Town", address: "Sundstorget 5", area: "centrum" },
  { name: "Clarion Hotel Sea U", address: "Kungsgatan 1", area: "hamnen" },
  { name: "Curry Nam Nam", address: "Bruksgatan 10", area: "centrum" },
  { name: "Diné Burgers", address: "Södra Kyrkogatan 12", area: "centrum" },
  { name: "Diplomat & Bar", address: "Sundstorget 3", area: "centrum" },
  { name: "Drottninggatan 35", address: "Drottninggatan 35", area: "centrum" },
  { name: "Ett litet Makeri", address: "Kungsgatan 12", area: "centrum" },
  { name: "Fahlmans", address: "Stortorget 11", area: "centrum" },
  { name: "First Camp Råå Vallar", address: "Kustgatan", area: "söder" },
  { name: "Fisk och skaldjur by Anette", address: "Marknadsvägen 9", area: "övrigt" },
  { name: "Fredriksborgs Gård", address: "Pålstorpsvägen 115", area: "norr" },
  { name: "Fria Bad & Bar", address: "Drottninggatan 95", area: "norr" },
  { name: "Frimurarlogernas Restaurant", address: "Stortorget 4", area: "centrum" },
  { name: "G o Co", address: "Marknadsvägen 9", area: "övrigt" },
  { name: "Gisela Trapps Krog & Kafé", address: "Oscar Trapps väg 10", area: "övrigt" },
  { name: "Goa Humlan", address: "Malmögatan 2", area: "söder" },
  { name: "Goa Punkten", address: "Gasverksgatan 35", area: "centrum" },
  { name: "Good Morning+ Helsingborg", address: "Gustav Adolfs Gata 47", area: "centrum" },
  { name: "Grekiska Kolgrillen", address: "Väla Restaurangtorget", area: "övrigt" },
  { name: "Grytan Restaurang", address: "Industrigatan 70", area: "övrigt" },
  { name: "Haket Restaurang", address: "Kullagatan 55", area: "centrum" },
  { name: "Hamnkrogen", address: "Hamntorget 2", area: "hamnen" },
  { name: "Happy Asian Food", address: "Ginstgatan 3", area: "övrigt" },
  { name: "Helsing Towers", address: "Slottshagsgatan 1", area: "centrum" },
  { name: "Helsingborg Arena", address: "Mellersta Stenbocksgatan 14", area: "övrigt" },
  { name: "Helsingborgen", address: "Furutorpsgatan 47", area: "centrum" },
  { name: "Helsingborgs Bryggeri", address: "Cindersgatan 4", area: "hamnen" },
  { name: "Helsingborgs Stadsteater", address: "Karl Johans gata 1", area: "centrum" },
  { name: "Helsingörskajen 10", address: "Helsingörskajen 10", area: "hamnen" },
  { name: "Home Hotel Grand", address: "Stortorget 8-12", area: "centrum" },
  { name: "Hotel Linnéa", address: "Prästgatan 4", area: "centrum" },
  { name: "Hotel Marina Plaza", address: "Kungstorget 6", area: "centrum" },
  { name: "Hotel Mollberg", address: "Stortorget 18", area: "centrum" },
  { name: "Hotell Stadsparken", address: "Bruksgatan 40", area: "centrum" },
  { name: "Hygge Restaurang & Bar", address: "Sundstorget 5", area: "centrum" },
  { name: "Icha Mochi", address: "Hjälmhultsgatan 8", area: "övrigt" },
  { name: "Icha Mochi City", address: "Sundstorget 1-3", area: "centrum" },
  { name: "Il Mio Ristorante", address: "Kungsgatan 2", area: "centrum" },
  { name: "Italy Espresso House", address: "Bruksgatan 30", area: "centrum" },
  { name: "K-Gränd", address: "Kolmätaregränden 7", area: "centrum" },
  { name: "Kajgatan 1", address: "Kajgatan 1", area: "hamnen" },
  { name: "Khai & Mui", address: "Kaliforniegatan 13", area: "övrigt" },
  { name: "Kings Corner", address: "Drottninggatan 1", area: "centrum" },
  { name: "Kitchen Floor", address: "Kungstorget 8", area: "centrum" },
  { name: "Kol & Cocktails", address: "Södra Storgatan 11-13", area: "centrum" },
  { name: "Koreana", address: "Bruksgatan 30", area: "centrum" },
  { name: "Krogen Wallåkra", address: "Drejarestigen", area: "övrigt" },
  { name: "Kryp In Café Vinbar", address: "Mariagatan 4", area: "centrum" },
  { name: "Kök 74", address: "Drottninggatan 74", area: "centrum" },
  { name: "Köket", address: "Sjögatan 1", area: "centrum" },
  { name: "Lagmark", address: "Roskildegatan 2", area: "centrum" },
  { name: "Lilla Bruket Tågaborg", address: "Tågagatan 31", area: "norr" },
  { name: "Lilla Spanjoren", address: "Kullagatan 60", area: "centrum" },
  { name: "Linnea & Basilika", address: "Drottninggatan 17", area: "centrum" },
  { name: "Linnéaträdgården", address: "Mariehällsvägen 100", area: "övrigt" },
  { name: "Lion Bar", address: "Bruksgatan 2", area: "centrum" },
  { name: "Loftet", address: "Tursköpsvägen 154", area: "övrigt" },
  { name: "Lottenlund Estate Events", address: "Lottenlundsvägen 2", area: "övrigt" },
  { name: "M/S Tilda", address: "Kungstorget 6 / Öresund", area: "hamnen" },
  { name: "Madame Moustache", address: "Norra Storgatan 9", area: "centrum" },
  { name: "Mamma Mia", address: "Elinebergsplatsen 5", area: "övrigt" },
  { name: "Mammas Kök", address: "Rååvägen 31", area: "söder" },
  { name: "MAVI", address: "Fågelsångsgatan 1", area: "centrum" },
  { name: "Miatorps Pizzeria", address: "Planteringsvägen 111", area: "övrigt" },
  { name: "Milano Restaurang & Pizzeria", address: "Ättekullagatan 2", area: "övrigt" },
  { name: "Mindpark", address: "Rönnowsgatan 8C", area: "centrum" },
  { name: "Miss Alice Krog & Butik", address: "Aspavägen 418", area: "övrigt" },
  { name: "Mittimellan", address: "Kajpromenaden 10", area: "hamnen" },
  { name: "Mörarps Pizzeria", address: "Bjuvsleden 11", area: "övrigt" },
  { name: "Nabo Matbar", address: "Drottninggatan 124", area: "norr" },
  { name: "Nancy's Steakhouse", address: "Marknadsvägen 9", area: "övrigt" },
  { name: "Nihon Sushi", address: "Badhusgatan 6", area: "centrum" },
  { name: "NOC/H", address: "Bruksgatan 2", area: "centrum" },
  { name: "Noise", address: "S Kyrkogatan 7", area: "centrum" },
  { name: "Norrbro Kök & Bar", address: "Norrbroplatsen 7", area: "centrum" },
  { name: "O'Learys Sportsbar", address: "Rådhustorget 10", area: "centrum" },
  { name: "Oasen Fonduerestaurang", address: "Bruksgatan 25", area: "centrum" },
  { name: "Odd Fellow", address: "Trädgårdsgatan 13", area: "centrum" },
  { name: "Old Times", address: "Bruksgatan 24", area: "centrum" },
  { name: "Olsons Skafferi", address: "Mariagatan 6", area: "centrum" },
  { name: "Olympia", address: "Filbornavägen 5", area: "övrigt" },
  { name: "Olympia Bowling", address: "Idrottens Hus", area: "övrigt" },
  { name: "Olympia Restaurang & Pizzeria", address: "Magnus Erikssons gata 8", area: "övrigt" },
  { name: "Omakaze Sushi", address: "Rydebäcks stationsgatan 51", area: "övrigt" },
  { name: "OSS Kitchen", address: "Himmelriksgränden 2", area: "centrum" },
  { name: "Oxhallen", address: "Cindersgatan 4", area: "hamnen" },
  { name: "Parapeten", address: "Hamnpiren, Norra Hamnen", area: "hamnen" },
  { name: "Pellegrino", address: "Norra Storgatan 15", area: "centrum" },
  { name: "Phuun Thai", address: "Hamntorget 3", area: "hamnen" },
  { name: "Phuun Thai Heden", address: "Planteringsvägen 112", area: "övrigt" },
  { name: "Pikado", address: "Landskronavägen 1-3", area: "övrigt" },
  { name: "Pinchos Söder", address: "Södergatan 32", area: "söder" },
  { name: "Pitcher's", address: "Södergatan 32", area: "söder" },
  { name: "Più 39 Trattoria Italiana", address: "Rååvägen 12", area: "söder" },
  { name: "Primo Il Forno", address: "Tågagatan 74", area: "norr" },
  { name: "Pronto i Påarp", address: "Ekebergavägen 3", area: "övrigt" },
  { name: "Pub Nessie", address: "Möllegränden 3", area: "centrum" },
  { name: "På Piren", address: "Hamnplan", area: "hamnen" },
  { name: "Påarps Pizzeria", address: "Lokföraregatan 24", area: "övrigt" },
  { name: "Pålsjö Krog", address: "Drottninggatan 151", area: "norr" },
  { name: "Pålsjöpaviljongen", address: "Pålsjöpaviljongen 2", area: "norr" },
  { name: "Radisson Blu Metropol", address: "Carl Krooks gata 16", area: "centrum" },
  { name: "Regio", address: "Drottninggatan 100", area: "norr" },
  { name: "Restaurang & Pizzeria i Bårslöv", address: "Snödroppegatan 1", area: "övrigt" },
  { name: "Restaurang Ankaret Råå", address: "Västindiegatan 22", area: "söder" },
  { name: "Restaurang Babou", address: "Kajpromenaden 21", area: "hamnen" },
  { name: "Restaurang Créo", address: "Bruksgatan 18", area: "centrum" },
  { name: "Restaurang Edelweiss", address: "Drottninggatan 15", area: "centrum" },
  { name: "Restaurang Le Cardinal", address: "Södra Kyrkogatan 9", area: "centrum" },
  { name: "Restaurang Marconi", address: "Drottninggatan 72", area: "centrum" },
  { name: "Restaurang Pub Ro", address: "Båthusgatan 11", area: "centrum" },
  { name: "Restaurang Rya", address: "Rya Golfbanevägen 20", area: "övrigt" },
  { name: "Restaurang Yoko", address: "Järnvägsgatan 3", area: "centrum" },
  { name: "Restaurangskolan", address: "Hamnpaviljongen, Parapeten", area: "hamnen" },
  { name: "Rocco's Wine & Dine", address: "Båthusgatan 15", area: "centrum" },
  { name: "Rodis Pizzeria", address: "Blåkullagatan 3", area: "övrigt" },
  { name: "Rosendal Slott", address: "Rosendal 107", area: "övrigt" },
  { name: "Rosengårdens Pizzeria", address: "Skaragatan 90", area: "övrigt" },
  { name: "Roys Fisk o Servering", address: "Kajpromenaden 21", area: "hamnen" },
  { name: "Rydebäcks Pizzeria", address: "Frösgatan 7", area: "övrigt" },
  { name: "Röda Kvarn", address: "Karlsgatan 7", area: "centrum" },
  { name: "Sams Bar", address: "Carl Krooks gata 50", area: "centrum" },
  { name: "Scandic Hotel", address: "Florettgatan 41", area: "övrigt" },
  { name: "Scandic Oceanhamnen", address: "Bröderna Pihls gränd 2", area: "hamnen" },
  { name: "Shark", address: "Södra Storgatan 16", area: "centrum" },
  { name: "Sillen & Makrillen", address: "Norra Gröningen 1", area: "hamnen" },
  { name: "Skonaren Nina", address: "Kajpromenaden", area: "hamnen" },
  { name: "Small Britain", address: "Rosendals Slott", area: "övrigt" },
  { name: "Sofiero Slott", address: "Sofierovägen 31", area: "norr" },
  { name: "Sofiero Orangeriet", address: "Sofierovägen 131", area: "norr" },
  { name: "Sorella", address: "Drottninggatan 88", area: "norr" },
  { name: "Spectrum", address: "Kullagatan 47", area: "centrum" },
  { name: "Spelpalatset", address: "Gasverksgatan 22", area: "centrum" },
  { name: "Strandhuset", address: "Drottninggatan 251", area: "norr" },
  { name: "Stubinen", address: "Drottninggatan 30", area: "centrum" },
  { name: "Sundsgårdens Folkhögskola", address: "Örbyvägen 10", area: "övrigt" },
  { name: "Suriyo Thai", address: "Pålsjögatan 8", area: "norr" },
  { name: "Taco Bar", address: "Södergatan 11", area: "söder" },
  { name: "Taj Mahal", address: "Drottninggatan 24", area: "centrum" },
  { name: "Tapasbar La Venta", address: "Mariagatan 8", area: "centrum" },
  { name: "Telegrafen", address: "Norra Storgatan 14", area: "centrum" },
  { name: "Teo's Kök & Bar", address: "Södergatan 60", area: "söder" },
  { name: "Thai Corner", address: "Bruksgatan 34", area: "centrum" },
  { name: "Thaikrogen", address: "Kurirgatan 1", area: "centrum" },
  { name: "The Filthy Fisherman", address: "Kolmätaregränden 8", area: "centrum" },
  { name: "The South Indian", address: "S:t Jörgens plats 8", area: "centrum" },
  { name: "The Tivoli", address: "Köpenhamnskajen 1", area: "hamnen" },
  { name: "The Vault Hotel", address: "Stortorget 20", area: "centrum" },
  { name: "Timjan & Tång", address: "Kajpromenaden 6", area: "hamnen" },
  { name: "Torget", address: "Sundstorget 7", area: "centrum" },
  { name: "Trivas på Råå", address: "Rååvägen 20", area: "söder" },
  { name: "Troppan", address: "Parapeten 1", area: "hamnen" },
  { name: "Tågvagnen", address: "Gröningen", area: "hamnen" },
  { name: "Utposten", address: "Stortorget 17", area: "centrum" },
  { name: "Utsikten", address: "Kajpromenaden 14", area: "hamnen" },
  { name: "Vagnhall 16", address: "Gåsebäcksvägen 2", area: "övrigt" },
  { name: "Vasatorp Golfrestaurang", address: "Vasatorpallén 54", area: "övrigt" },
  { name: "Ved By Maria", address: "Södra Kyrkogatan 22", area: "centrum" },
  { name: "Vegeriet", address: "Järnvägsgatan 25", area: "centrum" },
  { name: "Venezia Pizzeria", address: "Centralgatan 10", area: "övrigt" },
  { name: "Viking Bar", address: "Gasverksgatan 13", area: "centrum" },
  { name: "Villa Thalassa", address: "Dag Hammarskjölds Väg 117", area: "norr" },
  { name: "Wok Express", address: "Södra Brunnsvägen 57", area: "övrigt" },
  { name: "YA-HA Kök & Bar", address: "Kajpromenaden 2", area: "hamnen" },
  { name: "Yammi Söder", address: "Södergatan 30", area: "söder" },
  { name: "Yazhou", address: "Gasverksgatan 15", area: "centrum" },
  { name: "Zoom Bar & Restaurang", address: "Norra Kyrkogatan 15", area: "centrum" },
  { name: "Zushi Helsingborg", address: "Karlsgatan 1A", area: "centrum" },
  { name: "Zushi Ocean", address: "Oceankajen 2", area: "hamnen" },
  { name: "Ålgrändens Ost & Deli", address: "Ålgränden 6", area: "centrum" },
  { name: "Åliven", address: "Kullavägen 57", area: "norr" },
  { name: "Ödåkra Brygghus", address: "Fabriksgatan 2", area: "övrigt" },
  { name: "Öresundslinjen", address: "Färjeterminalen", area: "hamnen" }
];

const FUN_TAGLINES = [
  "Perfekt för att klaga på chefen! 😤",
  "Här kan ni äntligen prata om något annat än Jira-tickets! 🎫",
  "Garanterat inga standups här! 🙅",
  "Fredagsmys på riktigt! 🥳",
  "Bästa stället att diskutera Sprint Review... eller inte! 🏃",
  "Slack-notiser: OFF. Öl: ON. 🍺",
  "Här löser vi alla buggar... sociala buggar alltså! 🐛",
  "Teambuilding deluxe — inga isbrytarlekar krävs! 🧊",
  "Bättre än en Google Meet, garanterat! 💻",
  "Här behöver ingen dela skärm! 📺",
  "AW-kommittén har talat! 📢",
  "Perfekt avstånd från kontoret (mentalt och fysiskt)! 🏃‍♂️",
  "Inga agendapunkter, bara drinkar! 🍹",
  "Här gör vi retrospective på riktigt — med öl! 🍻",
  "Bästa stället att pitcha era dåliga idéer! 💡",
  "WiFi finns, men använd det INTE! 📵",
  "Kontorstofflorna stannar hemma! 👠",
  "Certifierat team-stärkande sedan 2025! 💪",
  "Chefen bjuder... kanske? 🤑",
  "Perfekt för att fira att det är fredag! 🎉",
  "Den inofficiella förlängningen av personalrummet! ☕",
  "Här sker de bästa korridorsnacken! 🗣️",
  "Bättre kultur än kulturpolicyn! 🎭",
  "100% mötesbefriad zon! 🚫",
  "Bästa stället att nätverka (aka skvallra)! 🤫",
  "Här laddar vi batterierna — med bubblor! 🫧",
  "Det bästa med jobbet! 💼",
  "Hellre här än framför en Excel! 📊",
  "Strategisk AW — dvs vi dricker och snackar! 🧠",
  "Kommunens bäst bevarade AW-hemlighet! 🤐"
];
